global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'placeholder1-service'
    static_configs:
      - targets: ['placeholder1-service:8082']

  - job_name: 'placeholder2-service'
    static_configs:
      - targets: ['placeholder2-service:8081']

  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'traefik'
    static_configs:
      - targets: ['proxy:8082']
